# Generated by Django 3.1.7 on 2021-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=300)),
                ('numeracion', models.CharField(max_length=6)),
                ('ciudad', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=400)),
                ('comuna', models.CharField(max_length=400)),
                ('cod_postal', models.CharField(max_length=20)),
            ],
        ),
    ]
