# Generated by Django 3.1.7 on 2021-06-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('nro_chip', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=6)),
                ('edad', models.CharField(max_length=15)),
                ('especie', models.CharField(max_length=5)),
                ('esterilizado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=300)),
                ('numeracion', models.CharField(max_length=6)),
                ('ciudad', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=400)),
                ('comuna', models.CharField(max_length=400)),
                ('cod_postal', models.CharField(max_length=20)),
            ],
        ),
    ]
