# Generated by Django 3.1.7 on 2021-06-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPeludo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='genero',
            new_name='sexo',
        ),
    ]
